trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.600'
  displayName: 'Install DotNetCore'
  
- script:
   dotnet build
  displayName: 'dotnet build'

- script:
   dotnet run
  displayName: 'dotnet run'
